# These are Global constants to use throughout the game

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

GAME_INTRO = 0
GAME_RUN = 1
GAME_DEATH = 2
GAME_WIN = 3

LASER_RADIUS = 11
LASER_SPEED = 10
LASER_LIFE = 60

SHIP_THRUST_AMOUNT = 3
SHIP_RADIUS = 18
SHIP_HEALTH = 15

BIG_ROCK_SPIN = 1
BIG_ROCK_SPEED = 1.5
BIG_ROCK_RADIUS = 23

MEDIUM_ROCK_SPIN = -2
MEDIUM_ROCK_RADIUS = 15

SMALL_ROCK_SPIN = 5
SMALL_ROCK_RADIUS = 9